# Generated by Django 3.2.2 on 2021-09-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Cancelled'), (2, 'Pending'), (3, 'Active')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bussines_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=14)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('tel', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=100)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address')),
                ('amenity', models.ManyToManyField(db_table='residence_residence_amenity', to='residence.Amenity')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ManyToManyField(db_table='residence_payment_methods_accepted', to='common.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.residence')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amenity', models.ManyToManyField(db_table='residence_room_amenity', to='residence.Amenity')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.residence')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.residencetype'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/residence')),
                ('main', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.residence')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
        ),
        migrations.CreateModel(
            name='BedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('date_from', models.DateField()),
                ('date_until', models.DateField(blank=True, null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.bed')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room'),
        ),
        migrations.AddField(
            model_name='bed',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residence.bedtype'),
        ),
    ]
