# Generated by Django 3.2.2 on 2021-08-22 15:28}
from django.db import models, migrations


RESIDENCE_TYPES = (
    (1, 'Mixta'),
    (2, 'Masculina'),
    (3, 'Femenina'),
)


def add_typres_codes(apps, schema_editor):
    ResidenceType = apps.get_model('residence', 'ResidenceType')
    for id, description in RESIDENCE_TYPES:
        typeres = ResidenceType(id=id, description=description)
        typeres.save()


BED_TYPES = (
    (1, 'Cama cucheta superior'),
    (2, 'Cama cucheta inferior'),
    (3, 'Cama una plaza'),
    (4, 'Cama dos plazas estándar'),
    (5, 'Cama dos plazas plaza y media'),
)


def add_bedtype_codes(apps, schema_editor):
    BedType = apps.get_model('residence', 'BedType')
    for id, description in BED_TYPES:
        bedtype = BedType(id=id, description=description)
        bedtype.save()


AMENITY_TYPES = (
    (1, 'Wifi'),
    (2, 'Sala de estudio'),
    (3, 'Computadoras de uso común'),
    (4, 'Baños equipados'),
    (5, 'Baño privado'),
    (6, 'Ventana a la calle'),
    (7, 'Ventana al patio'),
    (8, 'Alquiler de bicicletas'),
    (9, 'Lavandería'),
    (10, 'Desayuno'),
    (11, 'Traslado a tres cruces'),
    (12, 'Envío de remesas al interior'),
)


def add_amenitytype_codes(apps, schema_editor):
    AmenityType = apps.get_model('residence', 'Amenity')
    for id, description in AMENITY_TYPES:
        amenitytype = AmenityType(id=id, description=description)
        amenitytype.save()


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_typres_codes),
        migrations.RunPython(add_bedtype_codes),
        migrations.RunPython(add_amenitytype_codes),
    ]
