# Generated by Django 3.2.2 on 2021-09-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_load_intial_data_common'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='contact',
            new_name='address',
        ),
    ]
