# Generated by Django 3.2.2 on 2021-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_contact_institute_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/zones'),
        ),
    ]
