# Generated by Django 3.2.2 on 2021-11-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0004_zone_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('date_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_viewed', models.DateTimeField(blank=True, default=None, null=True)),
                ('from_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_mes', to=settings.AUTH_USER_MODEL)),
                ('to_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_mes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
