# Generated by Django 3.2.2 on 2021-09-28 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconsumed',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 28, 11, 0, 21, 94696, tzinfo=utc)),
        ),
    ]
