# Generated by Django 3.2.2 on 2021-09-30 10:27

from django.db import migrations, models
import reservation.models.payment
import reservation.models.reservation


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_serviceconsumed_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=reservation.models.payment.payment_path),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contract',
            field=models.FileField(blank=True, default=None, null=True, upload_to=reservation.models.reservation.contract_path),
        ),
    ]
