# Generated by Django 3.2.2 on 2021-10-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210930_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
