# Generated by Django 3.2.2 on 2021-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconsumed',
            name='date_cancelled',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='serviceconsumed',
            name='observations',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
